### ISSUE TITLE
Gui background flickering with crosshair hud

### ISSUE THREAD

**Issue by ManInMyVan** [moehreag/AxolotlClient-branding#82] opened 2023-07-13 21:27 UTC

**Comment by ghost** [comment] 2023-07-13 22:35
can you put a screenshot so i can know what kind of issue it is? I also have it,(i think) both kronhud and axol have a flicker issue

**Comment by moehreag** [comment] 2023-07-14 04:23
> can you put a screenshot so i can know what kind of issue it is? I also have it,(i think) both kronhud and axol have a flicker issue

What you think is quite likely the case. Please also add the Minecraft version you experience this on in addition to a Screenshot, it would help us fix this quite a lot. Thanks!

**Comment by ManInMyVan** [comment] 2023-07-14 04:42
> Please also add the Minecraft version you experience this on

1.19.4


> in addition to a Screenshot

Can't really use a screenshot since it flickers

**Comment by moehreag** [comment] 2023-07-14 04:56
> > in addition to a Screenshot
> 
> Can't really use a screenshot since it flickers
> 

If you can show it on a recording that'd be fine as well. Otherwise we'll just have to look for it ourselves.

**Comment by ManInMyVan** [comment] 2023-07-14 07:54
> we'll just have to look for it ourselves.

It's pretty noticeable, just turn on the crosshair hud, and press e, the dark background flickers.

If it doesn't happen for you, it might be one of my mods, I can get a list of them tomorrow

**Comment by moehreag** [comment] 2023-07-14 19:25
> > we'll just have to look for it ourselves.
> 
> It's pretty noticeable, just turn on the crosshair hud, and press e, the dark background flickers.
> 
> If it doesn't happen for you, it might be one of my mods, I can get a list of them tomorrow

I'm sorry we didn't have any luck trying to reproduce this, please see if it's caused by some other mod.

**Comment by ManInMyVan** [comment] 2023-07-14 21:40
[Exordium](https://modrinth.com/mod/exordium)

**Comment by moehreag** [comment] 2023-07-15 08:19
Would you mind to post a game log? It might be fixed in a newer version of Exordium. Otherwise I'd suggest removing Exordium since it's currently more or less unmaintained.

**Comment by ManInMyVan** [comment] 2023-07-15 17:36
I'll try updating and I'll send a log of it with the old & new version

**Comment by ManInMyVan** [comment] 2023-07-19 23:03
[Before Update](https://mclo.gs/KDKdxvK), [After Update](https://mclo.gs/1VlBntV)

**Comment by moehreag** [comment] 2023-07-20 05:59
> [Before Update](https://mclo.gs/KDKdxvK), [After Update](https://mclo.gs/1VlBntV)

The crash in the second log is caused by memoryleakfix. Try updating it or remove it if the crash persists (iirc it doesn't really do much anyway).

**Comment by ManInMyVan** [comment] 2023-07-20 22:28
After removing memoryleakfix it no longer crashes and the gui flickering no longer happens

**Closed as completed** 2023-07-21 05:19 UTC
Labels: bug
