### ISSUE TITLE
Overrides the Mod Menu Button

### ISSUE THREAD

**Issue by otter501** [moehreag/AxolotlClient-branding#65] opened 2023-02-21 06:38 UTC
When using Axolotl Client with [Mod Menu](https://modrinth.com/mod/modmenu) the Mods button will not show up

I don't know if mod menu support is something you wish to do, but it would be nice.

**Comment by moehreag** [comment] 2023-02-21 11:07
This is a known bug on the 1.16 versions and already fixed in the latest commits.

**Comment by TheKodeToad** [comment] 2023-02-21 11:08
I also observed this on 1.19 (from modrinth).

**Closed as completed by moehreag** 2023-02-21 11:07 UTC

**Comment by moehreag** [comment] 2023-02-21 11:12
I can't reproduce this on version 3.0.1+1.19.2, if you mean 1.19(.0) then it's probably an older version.

**Comment by orcachillin** [comment] 2023-02-21 11:21
Can reproduce this on 1.19.3

AC: 3.0.2-beta.3+1.19.3
MM: 5.1.0-beta.4

![image](https://user-images.githubusercontent.com/61361654/220331400-879a179f-d972-41fd-9612-b5851d9bc67d.png)

**Comment by moehreag** [comment] 2023-02-21 11:27
*I thought this was about the title screen..* Yes, in the Game Menu it seems to currently be missing, but that's not something that can't be fixed.

**Comment by TheKodeToad** [comment] 2023-02-21 11:30
Is it because mod menu looks for a button to place next to which it can't find? If so maybe there could be an option to hide the client options button since you can use a key anyway.

**Comment by moehreag** [comment] 2023-02-21 11:31
I would just have made the button not show up in case modmenu is installed since the options screen can also be accessed there.
