### ISSUE TITLE
Crash on Title Screen

### ISSUE THREAD

**Issue by NotAlexNoyle** [moehreag/AxolotlClient-branding#40] opened 2022-11-12 23:57 UTC
My title screen only displays a dirt block pattern. This error is shown in the console:

https://pastebin.com/raw/dSYwhGs7

Prism Launcher, 1.19.2

**Comment by moehreag** [comment] 2022-11-13 00:21
The error you attached is likely to be caused by one of your resourcepacks. If you look into the path `assets/minecraft/optifine/sky/world0/` you might be able to find a properties file that does __not__ state `source=<file>`. 

The logged error should not cause a misbehaving title screen though, that might be caused by a different mod. Since you didn't attach a full log, I can't try to find which one it is for you.

**Comment by moehreag** [comment] 2022-11-13 16:28
Additionally, the error output should now be gone as of https://github.com/AxolotlClient/AxolotlClient-mod/commit/23d33c38adf4dfa3ed3e613bd218acb25f9fe3dc.

**Comment by NotAlexNoyle** [comment] 2022-11-22 20:05
The error output is indeed gone on the new build but the behavior is unchanged. I checked my resource packs and I didn't see any source property definitions missing. Here is my mod list:

` 1.19.2
  [✔] AdvancedChatCore-1.19.2-1.5.8
  [✔] AdvancedChatHUD-1.19.1-1.3.4
  [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔] alternate-current-mc1.19-1.4.0
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] architectury-6.3.56-fabric
  [✔] AxolotlClient-2.2.4+1.19.2
  [✔] badpackets-fabric-0.2.1
  [✔] betterbeds-1.2.0
  [✔] BetterF3-4.0.0-Fabric-1.19.2
  [✔] Blanket Client tweaks-1.1.2
  [✔] bobby-4.0.1
  [✔] Bookshelf-Fabric-1.19.2-16.1.11
  [✔] brb-1.6.0-fabric
  [✔] bsvsb-3.0.2
  [✔] charmonium-fabric-1.19.2-4.2.1
  [✔] CITResewn-1.1.2+1.19.2
  [✔] clear-skies-fabric-mc119-2.0.95
  [✔] clientcommands-2.7.4
  [✔] cloth-config-8.2.88-fabric
  [✔] completeconfig-2.1.0
  [✔] continuity-2.0.1+1.19
  [✔] dashloader-4.1.3+1.19
  [✔] Debugify-2.8.0
  [✔] DimThread-1.2.7
  [✔] DisableCustomWorldsAdvice-3.0
  [✔] EnchantmentDescriptions-Fabric-1.19.2-13.0.10
  [✔] enhancedblockentities-0.7.2+1.19.2
  [✔] Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0
  [✔] entity_texture_features_fabric_1.19.2-4.2.0
  [✔] entityculling-fabric-1.5.2-mc1.19
  [✔] fabricskyboxes-0.6.0+mc1.19.2
  [✔] fabrishot-1.9.1
  [✔] fallingleaves-1.13.0+1.19.2
  [✔] ferritecore-5.0.0-fabric
  [✔] forcecloseloadingscreen-1.1.1
  [✔] fsb-interop-1.0.0-SNAPSHOT
  [✔] Gamma-Utils-1.6.10-mc1.19.2
  [✔] indium-1.0.9+mc1.19.2
  [✔] inspecio-1.6.0+1.19
  [✔] iris-mc1.19.2-1.5.0-shadowcomp-cu-test.1-060e1943-dirty
  [✔] Jade-1.19.1-fabric-8.6.0
  [✔] joml-1.10.4
  [✔] krypton-0.2.1
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.1.2+1.19
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.2-0.10.2
  [✔] lwjgl-vulkan-3.3.1
  [✔] malilib-fabric-1.19.2-0.13.0
  [✔] memoryleakfix-1.19.1-0.7.0
  [✔] memoryusagescreen-fabric-mc1.19-1.6
  [✔] mipmaplevelandlanguagefix-1.0.0+1.16_to_1.19
  [✔] mixintrace-1.1.1+1.17
  [✔] modmenu-4.1.1
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moremusic-0.1.3+1.19
  [✔] MTTBWY-1.19.2-1.0.0
  [✔] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✔] NostalgicTweaks-Fabric-1.19.2-1.2.2
  [✔] notenoughcrashes-4.2.0+1.19.2-fabric
  [✔] optigui-1.1.6
  [✔] phosphor-fabric-mc1.19.x-0.8.1
  [✔] purpurclient-1.19.2-16
  [✔] quilt-kotlin-libraries-0.1.2-MODFEST+kt.1.7.10+flk.1.8.2
  [✔] quilted-fabric-api-4.0.0-beta.19+local-0.64.0-1.19.2
  [✔] raised-fabric-1.19.2-1.1.4
  [✔] reeses_sodium_options-1.4.7+mc1.19.2-build.59
  [✔] replaymod-1.19.1-2.6.8
  [✔] resounding-1.0.0-bc.19.x
  [✔] screenshot-to-clipboard-1.0.9-fabric
  [✔] servercore-1.3.3-1.19.2
  [✔] servertick-mc1.19-1.7
  [✔] ShieldDisruptor-1.4.0+1.19
  [✔] sodium-extra-0.4.13+mc1.19.2-build.76
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] sodium-shadowy-path-blocks-3.1.0
  [✔] spark-1.9.45-fabric
  [✔] statuseffecttimer-1.1.1+1.19
  [✔] swordblocking-1.1.0
  [✔] technomodel-1.0.2
  [✔] thorium-1.3.2
  [✔] tooltipfix-1.1.0-1.19
  [✔] uglyscoreboardfix-2.7.0
  [✔] vmp-fabric-mc1.19.2-0.2.0+beta.7.12-all
  [✔] Xaeros_Minimap_22.16.2_Fabric_1.19.1
  [✔] YetAnotherConfigLib-1.7.1`

**Comment by moehreag** [comment] 2022-11-22 20:11
Thank you for the update, though could you please also attach a _full_ log since I can't figure out from just the list what mod could cause that? (if you're worried about personal data you can also use Prism's "Upload Log" feature which uses mclo.gs and automatically redacts any personal information)

**Comment by NotAlexNoyle** [comment] 2022-11-22 21:15
> Thank you for the update, though could you please also attach a _full_ log since I can't figure out from just the list what mod could cause that? (if you're worried about personal data you can also use Prism's "Upload Log" feature which uses mclo.gs and automatically redacts any personal information)

https://mclo.gs/U5ouwdR

**Comment by moehreag** [comment] 2022-11-22 21:35
Thank you, I can spot a mixin conflict with ReplayMod which will be fixed in a few minutes, otherwise you have a few mods installed whose functionality is already provided by other mods, e.g. UglyScoreboardFix, which is also provided in this mod (These aren't compatibility issues though, you can just keep using them if preferred). Other than that, there is sadly still the possibility for Dashloader to mess up resource loading even though its compatibility has vastly improved since version 3.0.0. If after the first fix mentioned here the issue still persists I would recommend a binary search to track down what combination of mods exactly cause the issue.

**Comment by moehreag** [comment] 2022-11-22 22:16
Furthermore, after a little bit of testing, a dirt background on the title screen is made available by NostalgicTweaks, but can be disabled in its config if wanted. Sadly I can't see a crash in the log you sent, so this is the only other assumption I can make.

**Comment by NotAlexNoyle** [comment] 2022-11-23 06:28
Thanks for the ReplayMod patch. The reason I use UglyScoreboardFix is because Axolotl's scoreboard module displays as transparent (besides a small strip near the top). Screenshot [here](https://i.imgur.com/dU8MNDc.jpg). Is this a bug? I have the background enabled in settings.

If you noticed any other mods that do the same thing, I'd be interested to know, since having multiple that do the same thing isn't my intention.

NostalgicTweaks was the culprit behind the dirt background, thank  you. The issue can be closed.

By the way, how do I build AxolotlClient while specifying which minecraft version to target?

**Comment by moehreag** [comment] 2022-11-23 06:49
Yes, I suppose the scoreboard has a bug, it will be fixed after school (sorry). Since you asked, the different versions are in separate branches of the repository. If you're too lazy to build them yourself github actions is available as well. If possible I'd like to keep it open until all bugs you find are fixed if that's fine for you. Thanks for the help with finding those as our time can be rather limited!

**Comment by NotAlexNoyle** [comment] 2022-11-24 16:52
The scoreboard is fixed in the latest build, and so is the invisible crosshair problem I was having.

The last issue I notice is incorrect strings in the sprinting/shifting indicator in the bottom right (https://i.imgur.com/e6OgMh1.jpg)

**Comment by moehreag** [comment] 2022-11-24 17:08
Thank you, these are now fixed as well. If you find any more bugs please be sure to let us know either here on github or on [discord](https://discord.gg/9Q3brQVQZN)!

**Comment by NotAlexNoyle** [comment] 2022-11-24 17:22
Yep it's fixed, thank you.

**Closed as completed** 2022-11-24 17:23 UTC
